version: '3.8'

services:
  python_app:
    build: .
    container_name: python_app_container
    ports:
      - "5001:5000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - app_network

  redis:
    image: "redis:latest"
    container_name: redis_container
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
